# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca38d45c30bcf98363bfa9bdaadbbeb78ad99892c88db01d0c625f8a9cb01e4d26add5b4955d0c2342eef2980e521148746d18d4be05a1b199cb694c61fcc45d

test:
  secret_key_base: 798dda5c2b7fc0cbf4894eab5c5d3d5d61bff6f840ac823b21d2c5e6ae9f9f36549e2cc6db88bf144f76fbaa5f09fd366678a8f0311665b48047f510e130255b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
